// Generated by Wrangler by running `wrangler types ./src/server/worker-configuration.d.ts`

interface Env {
	TRANSFER_STATUS: KVNamespace;
	TransferStatusServer: DurableObjectNamespace /* TransferStatusServer */;
	ASSETS: Fetcher;
}
