// Generated by Wrangler by running `wrangler types`

interface Env {
  TRANSFER_STATUS: KVNamespace;
  SUBSCRIBE_HMAC: string;
  UPDATE_HMAC: string;
  TransferStatusServer: DurableObjectNamespace<
    import("./index").TransferStatusServer
  >;
  ASSETS: Fetcher;
}
