// Generated by Wrangler by running `wrangler types`

import { KVNamespace, D1Database, Fetcher } from "@cloudflare/workers-types"

interface Env {
  TRANSFER_MAPPINGS: KVNamespace
  SHOPIFY_CHECKOUT_SESSION_KV: KVNamespace
  API_DOMAIN: "mm24mwlpnd.execute-api.us-east-1.amazonaws.com"
  VITE_AUTH0_DOMAIN: "zenobia-beta.us.auth0.com"
  VITE_AUTH0_CLIENT_ID: "gRg4qNX32qmtoLOUH8wmojid0So9MkqB"
  VITE_API_BASE_URL: "https://mm24mwlpnd.execute-api.us-east-1.amazonaws.com/Prod"
  BIGCOMMERCE_CLIENT_ID: string
  BIGCOMMERCE_CLIENT_SECRET: string
  ACCOUNTS_DOMAIN: string
  ACCOUNTS_AUDIENCE: string
  ZENOBIA_CLIENT_ID: string
  ZENOBIA_CLIENT_SECRET: string
  SHOPIFY_CLIENT_ID: string
  SHOPIFY_CLIENT_SECRET: string
  SHOPIFY_ENCRYPTION_KEY: string
  SHOPIFY_PROXY_SECRET: string
  API_BASE_URL: string
  MERCHANTS_OAUTH: D1Database
  ASSETS: Fetcher

  SUBSCRIBE_HMAC: string
}
