name = "dashboard"
compatibility_date = "2024-03-20"
main = "src/worker.ts"

[build]
command = "vite build"

[dev]
port = 3000
local_protocol = "http"

[observability.logs]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# D1 Database binding
[[d1_databases]]
binding = "MERCHANTS_OAUTH"
database_name = "merchants-oauth"
database_id = "07a2a748-ace8-4ae0-90f4-591de430feb1"

# KV Namespace bindings
[[kv_namespaces]]
binding = "TRANSFER_MAPPINGS"
id = "a108119636444e439b3a821965f0d510"

[[kv_namespaces]]
binding = "SHOPIFY_CHECKOUT_SESSION_KV"
id = "ae8baf2ae18e4722be0338bffb10c314"

[vars]
# Auth0 related
ACCOUNTS_DOMAIN = "https://accounts.zenobiapay.com"
ACCOUNTS_AUDIENCE = "https://dashboard.zenobiapay.com"
ZENOBIA_CLIENT_ID = "THPfLUrf2wgJmgnSIPIGrZIb8W0GpUqA"

API_BASE_URL = "https://api.zenobiapay.com"

# BigCommerce related
BIGCOMMERCE_CLIENT_ID = "c1cohhttoxpeq0pjltju1clo1djme0g"

# Shopify related
SHOPIFY_CLIENT_ID = "2e0bcf59a2683f29d5f70770020da601"

# Vite specific variables
VITE_AUTH0_DOMAIN = "accounts.zenobiapay.com"
VITE_AUTH0_CLIENT_ID = "l9yWBIfzSVWjMMHP02BS6if4VeZVFViH"
VITE_API_BASE_URL = "https://api.zenobiapay.com"
