name = "zenobia-dashboard"
compatibility_date = "2024-03-20"
main = "src/worker.ts"

[build]
command = "vite build"

[dev]
port = 3000
local_protocol = "http"

[observability.logs]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
