name = "landing-page"
main = ".output/server/index.mjs"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

[site]
bucket = ".output/public"

[build]
command = "npm run build"

[env.production]
name = "landing-page"

[env.staging]
name = "landing-page-staging"